name: Feature request
description: File a feature request
title: "[Feat]: "
labels: ["feature", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: file
    attributes:
      label: File
      description: Which Figma file is affected?
      options:
        - Design system UI kit
        - Patterns & apps
        - Mobile patterns
        - Light theme
        - Dark theme
        - User flow kit
        - Persona template
        - Design thinking workshop
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What is your need?
      description: Tell us about your need?
      placeholder: Tell us what you need!
      value: "A wonderful feature!"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
